name: Release Trakr Binary

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
      
jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
          check-latest: true

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/trakr-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o dist/trakr-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -o dist/trakr-windows-amd64.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
